sudo: required
services:
- docker
language: go
branches:
  only:
  - master
go:
- '1.17'
env:
  global:
  - GH_REF: github.com/tomologic/couchlock.git
  - secure: S2joiB8plRG5hl+G4wq/WxvW8GHV3/bpQK1yl3xUjo+03gCCMeT0BFDhNkhuLK4BwbFTAPtfdhpZ/g3ytf/ucn0r+74Sa43iKco2Avb8ti7LLnGaeNWtkoFGVhXpYWNc7JX2KEWWH48R1SujPCVUFbrUIwFZvfuYawbqI04UGscse1dQKAJM23wXrbeVOnPUi67RKZu2YIMxX6LQr3Ay/RfcDlGsiVpRBNPzjlt5/jEnzbkIL50I5iw+UBGsN7Dt92GSGWSbFMJYmBYu1xsZF6OL5un7ZG1XIq6PePvS6b2hvsJOhf/x64A6R1OO/77PwM0mFrX2lQGHjCv9Ohzpj2VvLtFdRT3BGiYONxvv2BEF/NxcLT4HMCTDLNIBUZz3lGTvmJAFFXti5csF+PLT4V++OQcmUrKeSDaDNiW5a4Gm5eL+1GHiaoJdItgPA4dJsROLhZm0QTW746TsdTcROgzVYQKZtVwMmTtaEhXU46/1PTy7NbC/5+TUXvFtRx3zXckmT+cKFLpXxZvmTLsXgZ3eszTnOXWzyKOXz+UhuvYIj/P/b03zuHFz23HNxlaClLNJ7veGL+3SguDZ0E5XHZy+7/CxMwL0hU1VQmM/0b975iGqFywLQVsCU4rF2j/vP1WuuxFVPcOJ9GfCJXc4xHxTENL8qSyfnYgY4hg0If4=
install:
- git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
- export PATH="$HOME/.linuxbrew/bin:$PATH"
- brew install tomologic/tap/travis-ci-bumpminor-sh
- brew install bats
- gem install fpm --no-ri --no-rdoc
- sudo apt-get update -qq
- sudo apt-get install -qq -y rpm
- go get -t ./...
script:
- go test ./... -v
- go vet ./...
- bats ./bats
before_deploy: |
  # Bump version
  travis-ci-bumpminor.sh

  # Build
  make build
  make package
deploy:
  provider: releases
  api_key:
    secure: H2kvIaYOMbkEclPAQS+wKAWHlsMCzBrO+ezWGYJ9PMVdiBJoWDDmzU/FJ13EjM0HjtTM93H721Iu/M7z7fgrXg8N+PaOawE82XG3OtcrwU8oXlAqqco5JD1ZB9mJ8FbhVPL5atKUgQxlaaR8FTiV1u4bxJnvBD4M6IKRjcp5z5rl79YsdGL5Oyxsw6DWvFZEA8Ndk4kUCr+RmhRhh6FZnp6LHFOxt6JWpBkSAJOMCmKILvrOFjauzoNNJLpqeb7BUgiRKf76d8BZArQFSiuwYdjPQFnMs5dnnpj1ncIB4iQzDFVUgbHBWcGrW+w5n2H9afRSoB+q/Qd/mVY4Wu18XiLg5q/l7/R9/FVN11D7d6O8rWh+cuiWeH4kjnNqImoaErST0Cuy4GMrgylDE1EfOdk4GzZdfDMyfZjC1wv1QDmnUopA96y+H/1sWHbLb26Gq+e+62jSfcTW6CvVMhrY8Kv38AjGiFFxNKC7wmqafmvvqVci4vemib4pjRDzaeCJe5/KAX3NnvqZgmf3+Z7YnNRyqHLcZTu6/m379fxZCl5vGydID/fcNtHRdHh0ommUYZgVEiEDqP4A1lOTE0J1hLQyx/oYBW4ZkU0INk3QQU1H1dDGnGRpuabWJ4HSvKm9Bm1zXkNfiNQhSqPcEHgdZjQW5Y0mOEpVbg7Qh4n6LzI=
  file: ARTIFACTS/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: tomologic/couchlock
